spring.application.name=email-writer

#gemini.api.url = ${GEMINI_API_URL}
#gemini.api.key = ${GEMINI_API_KEY}

gemini.api.url=https://generativelanguage.googleapis.com
gemini.api.key=AIzaSyB7PhoeakqQsIzsiLZNi-Oyh61VQW5tw-M

server.port=8090